apiVersion: v2
name: nodejs-app
description: A Helm chart for Node.js application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - nodejs
  - web
  - application
maintainers:
  - name: Tsenko Tsenkov
    email: tseni.tsenkov@gmail.com
sources:
  - https://github.com/TsenkoTsenkov/2bcloud-assignment
