# Default values for nodejs-app.
replicaCount: 1

image:
  repository: __ACR_NAME__.azurecr.io/nodejs-app
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

healthChecks:
  enabled: true
  livenessProbe:
    path: /healthz
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 5

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Additional configurations
nodeSelector: {}
tolerations: []
affinity: {}
